### ISSUE TITLE
关于生成的base64的问题

### ISSUE THREAD

**Issue by wevsmy** [AmazingDM/sub#1]
您好  关于生成的base64在解码过程有误，

通过在线解码工具可以解码

但是通过v2rayN 订阅，无法解码，  瞅瞅源码，发现时base64在编码的过程中，最后一天VMess连接 少了一个换行符，导致编码后C#无法解码，即v2rayN订阅不成功。

大佬有空看看，是什么问题！

**Comment by AmazingDM** [comment]
已解决
